### ISSUE TITLE
Auth not quite working

### ISSUE THREAD

**Issue by dogweather** [cfjedimaster/githubhealth#1]
Hi, I realize the code is just a simple spike effort, but I tried the online demo you've set up and wasn't able to get past the authentication/authorization stage. Any ideas why it might not be working?

**Comment by cfjedimaster** [comment]
No - I wonder if something has changed and I need to update to the latest Hello library.

**Comment by dogweather** [comment]
Could be. FYI, I'm extremely interested in this same concept. Maybe we can work together: https://github.com/dogweather/repo-health-check

**Comment by cfjedimaster** [comment]
I'm not really planning on doing much more with this, but if you want to take anything from me, I'm fine with it for sure.

**Comment by cfjedimaster** [comment]
Can you try here and confirm it works for you: http://static.raymondcamden.com/githubhealth/

**Comment by dogweather** [comment]
Exellent! That worked.

**Comment by cfjedimaster** [comment]
Thanks - I need to push up the code here and update my blog entry.
